# fly.toml app configuration file generated for health-bot-dry-cloud-653 on 2026-01-26T00:12:41-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'health-bot-dry-cloud-653'
primary_region = 'gru'

[build]

[env]
  TZ = 'America/Sao_Paulo'

[processes]
  bot = 'python -m bot.main'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
